#!/usr/bin/env bash

APP="echo_bot"

LINK_SYS_CONFIG=/etc/echo_bot.config

BUILD_HOST="bothub.colharris.com"
BUILD_USER="root"
BUILD_AT="/git/echo_bot/builds"
RELEASE_DIR="/git/echo_bot/builds/rel/echo_bot"

STAGING_HOSTS="bothub.colharris.com"
STAGING_USER="git"
TEST_AT="/test/echo_bot"

PRODUCTION_HOSTS="bothub.colharris.com"
PRODUCTION_USER="root"
DELIVER_TO="/opt/echo_bot"
